## -*- makefile -*- for 32-bit MS-Windows
CC = i586-mingw32msvc-gcc
CFLAGS = -Wall -O3 -mno-cygwin
LDFLAGS = -s

EXE =.exe

all: zip

include Makefile

zip: COPYING ChangeLog cbmconvert.html $(MANPAGES:.1=.txt) $(TARGETS)
	zip -l cbmconvert.zip COPYING ChangeLog cbmconvert.html \
		$(MANPAGES:.1=.txt)
	zip cbmconvert.zip $(TARGETS)
